iss:
  api:
    url: "https://api.wheretheiss.at/v1/satellites/25544"
    timeout: 10
    rate_limit: 5
  max_rows: 10

log:
  file:
    name: "iseeiss.log"
    level: "INFO"
    max_bytes: 1048576
    formatter: "default"
  console:
    level: "INFO"
    stream: "ext://sys.stdout"
    formatter: "default"
  format: "[%(asctime)s] %(levelname)s in %(module)s: %(message)s"
