DROP TABLE IF EXISTS iss;

CREATE TABLE iss (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);